center_x: 0.0
center_y: 0.0
center_z: 0.0
docking_engine: AutoDock Vina
exhaustiveness: 8
grid_size: 20
pocket_known: true
pocket_residues: B:21,B:22,B:23,B:24,B:25,B:26,B:27,B:102,B:250,B:251,B:252,B:253,B:256,B:406,B:410
receptor_path: data/inputs/target.pdb
structure_known: true
